import youtube from "../img/youtube.png"
export const tokens = [
    {
      id: 1,
      name: "PewDiePie Coin",
      creator: "PewDiePie",
      price: 12.45,
      change: 15.2,
      volume: "1.2M",
      subscribers: "111M",
      image: youtube,
    },
    {
      id: 2,
      name: "MrBeast Coin",
      creator: "MrBeast",
      price: 45.78,
      change: 8.7,
      volume: "2.5M",
      subscribers: "98M",
      image: youtube,
    },
    {
      id: 3,
      name: "Markiplier Coin",
      creator: "Markiplier",
      price: 8.92,
      change: -3.4,
      volume: "892K",
      subscribers: "34M",
      image: youtube,
    },
    {
      id: 4,
      name: "MKBHD Coin",
      creator: "Marques Brownlee",
      price: 32.5,
      change: 5.6,
      volume: "1.5M",
      subscribers: "15M",
      image: youtube,
    },
    {
      id: 5,
      name: "Linus Coin",
      creator: "Linus Tech Tips",
      price: 28.15,
      change: -2.1,
      volume: "950K",
      subscribers: "15M",
      image: youtube,
    },
    {
      id: 6,
      name: "VSauce Coin",
      creator: "VSauce",
      price: 15.3,
      change: 7.8,
      volume: "780K",
      subscribers: "18M",
      image: youtube,
    },
    {
      id: 7,
      name: "VanossGaming Coin",
      creator: "VanossGaming",
      price: 22.45,
      change: -1.2,
      volume: "1.1M",
      subscribers: "25M",
      image: youtube,
    },
    {
      id: 8,
      name: "Ninja Coin",
      creator: "Ninja",
      price: 18.75,
      change: 3.9,
      volume: "2.2M",
      subscribers: "24M",
      image: youtube,
    },
    {
      id: 9,
      name: "JackSepticeye Coin",
      creator: "JackSepticeye",
      price: 11.2,
      change: -4.5,
      volume: "650K",
      subscribers: "29M",
      image: youtube,
    },
    {
      id: 10,
      name: "DanTDM Coin",
      creator: "DanTDM",
      price: 9.85,
      change: 6.3,
      volume: "890K",
      subscribers: "26M",
      image: youtube,
    },
    {
      id: 11,
      name: "Casey Neistat Coin",
      creator: "Casey Neistat",
      price: 25.6,
      change: -2.8,
      volume: "1.3M",
      subscribers: "12M",
      image: youtube,
    },
    {
      id: 12,
      name: "KSI Coin",
      creator: "KSI",
      price: 33.9,
      change: 12.4,
      volume: "3.1M",
      subscribers: "24M",
      image: youtube,
    },
  ]